package com.hr.ai.model.enums;

public enum HrQueryIntent {
    PERSONAL_PROFILE,
    PERSONAL_LEAVE,
    PERSONAL_OVERTIME,
    PERSONAL_ATTENDANCE,
    PERSONAL_SALARY,
    PERSONAL_PERFORMANCE,
    DEPT_OVERTIME,
    DEPT_HEADCOUNT,
    DEPT_TURNOVER,
    DEPT_PERFORMANCE,
    DEPT_SALARY,
    COMPANY_OVERVIEW,
    TEXT_TO_SQL,
    KNOWLEDGE
}
